spatie/laravel-html

- src/Elements/Select.php
- src/Html.php
- tests/Elements/SelectTest.php
Here's my take on implementing multiple select support (https://github.com/spatie/laravel-html/pull/20). I think it's cleaner to introduce a `multiple()` method on the `Select` class instead of creating `multiselect()` in the `Html` class.
Some explanation:
* the `applyValueToOptions()` method is modified to always compare against a collection.
* In case of a single select, the collection will always contain one value to get expected behavior, even though multiple values were provided. 
* In case of a multiple select, the collection will just pass through and select all applicable options.
* Since creating a new `Select` using the `Html` class automatically calls `value()`, hence already setting the selected options to those of a single select, the `multiple()` method calls …
> Implement support for multiple select

- src/BaseElement.php
- tests/BaseElementTest.php
This PR adds a convenient `->data()` method to `BaseElement`.
```blade
{{ html()->div()->data('foo', 'bar') }}
```
which will be rendered as
```html
<div data-foo="bar"></div>
```
> add convenient data method

- src/BaseElement.php
- src/Elements/A.php
- src/Elements/Button.php
- src/Elements/Div.php
- src/Elements/Element.php
- src/Elements/Fieldset.php
- src/Elements/File.php
- src/Elements/Form.php
- src/Elements/Input.php
- src/Elements/Label.php
- src/Elements/Legend.php
- src/Elements/Optgroup.php
- src/Elements/Option.php
- src/Elements/Select.php
- src/Elements/Span.php
- src/Elements/Textarea.php
- tests/BaseElementTest.php
With this PR, every single method of `BaseElement` (and children) have a `if` version.
```php
html()->span()
->styleIf($hidden, 'display: none')
->classIf($class_name !== null, $class)
```
This will allow to lighten the html code generated (and/or the logic in the blade file).
Ofc `BaseElement::attributeIf` is removed here
Tests are provided (and existing `attributeIf` still pass)
> If all the things

- src/Html.php
- tests/Html/CheckboxTest.php
- tests/Html/RadioTest.php
Trying to set 0 as a value of an input resulted in no value being set, this allows zero to be used.
> Allow <input ... value="0">

- src/Html.php
- tests/Html/OldTest.php
Special case when a field value is `0`. Added tests for both sessions and models.
> Allow input to populate value with `0` successfully

- src/BaseElement.php
- tests/BaseElementTest.php
An interesting case I came across recently. In a blade component, I set a submit button:
{{ html()->submit($slot)->class('btn btn-primary') }}
which allows me to set the button text in another blade file as HTML (rather than a string):
@component('layout.forms.submit')
<span class="fa fa-plus" aria-hidden="true"></span> Add user
@endcomponent
However, `$slot` is passed as `Illuminate\Support\HtmlString` to `BaseElement::html()`. Previously the `html()` function would add this blindly to the children array, and then rendering would fail when it encountered the `HtmlString`.
Calling `setChildren()` from `html()` converts the `HtmlString` to a string that can be handled correctly.
> Use setChildren() when calling html() on an element

- src/Html.php
- tests/Html/CheckboxTest.php
The checkbox input should not pull its _value_ from old/session input - that should only affect whether it is _checked_.
An example: we are displaying a boolean value as a checkbox. The boolean is stored as 0 or 1 in the model. If the boolean is currently 0, then the checkbox will be generated as:
<input type="checkbox" name="name" id="name" value="0">
When this form is posted with the checkbox checked, `name` will be set to `0`... which may be interpreted as false. In this case, the boolean can never be set to true again.
I believe this behaviour started after PR #69 was merged.
> Fix checkbox values

- composer.json
https://github.com/spatie/laravel-html/blob/55a367862d61a46620bc04ec1dd2ae24c16c470e/composer.json#L27
Upgraded my project to Laravel 5.6, but spatie/laravel-html won't come along 😊 Dependencies for 2.12 are still locked at 5.4 and 5.5.
This should fix it:
```
"require": {
"php": "^7.0",
"illuminate/http": "~5.4.0|~5.5.0|~5.6.0",
"illuminate/support": "~5.4.0|~5.5.0|~5.6.0"
},
```
Also an option is to just depend on the minimum version:
https://github.com/sebastiaanluca/laravel-router/blob/master/composer.json#L24
This allows your package to be used in any version upwards of the minimum requirement, without having to upgrade whenever a new release comes out. Of course, it can happen something breaks, but since it can be used ahead of time, users can notify you of this in advance.
> Update dependencies for Laravel 5.6 compatibility

- src/Html.php
- tests/Concerns/AssertsHtmlStrings.php
- tests/Html/InputTest.php
Adds input convenience methods for:
```html
<input type="date">
<input type="time">
```
I skipped `datetime-local` because browser support is far better for `date` and `time` so it's better to use that combo at the time of this PR 🥂
> Add date and time convenience methods

- src/Elements/Input.php
- tests/Elements/InputTest.php
This feature is already possible for marking an input as disabled, but not for the required attribute.
Instead of writing this:
```php
@if(true)
{{ html()->input('name')->required() }}
@else
{{ html()->input('name') }}
@endif
```
We can write it like this:
```php
{{ html()->input('name')->required(false) }}
```
which will not add the required attribute to the input.
> Allow passing a boolean for making a field required.

- src/Html.php
- tests/Html/OldTest.php
Say you've got some model attributes, but they're part of an array (maybe JSON) or a relation. Currently these aren't retrieved and prefilled when you're using a model to build your form.
E.g. an address model linked to the model you're using for the form:
```php
{{ html()->text('address[city]') }}
```
This PR makes use of `data_get()` to get the attribute using dot notation.
Need to add a test for this, but my local PHP setup is botched so I can't install any vendor packages. Need to get that sorted first, maybe you guys are faster ;)
> Automatically prefill form array attributes from the model

- src/Html.php
- tests/Html/FormTest.php
- tests/Html/MailToTest.php
Avoid need to pass email address twice to mailto().
> Default to email address for mailto, fix failing test

- src/BaseElement.php
- tests/BaseElementTest.php
As described in the title, this feature adds the ability to reverse the `if()` method.
Example: 
```php
Div::create()->unless(false, function (Div $div) {
return $div->addClass('foo');
});
// OR
Div::create()->attributeUnless(false, 'class', 'foo');
```
> Adding the `unless` conditional method

- src/BaseElement.php
Sometimes I need to add a valueless data attribute, so it would be more interesting to leave the value optional to get simpler.
```blade
{{ html()->hidden('example')->data('example', null) }}
-> <input type="hidden" name="example" id="example" example>
vs
{{ html()->hidden('example')->data('example') }}
-> <input type="hidden" name="example" id="example" example>
```
> Add null to data value

- src/Html.php
- tests/Html/OldTest.php
Fixed form population (using **modelForm**) when was specified 0 (zero) as field value:
```php
// if $model->price doesn't exists
html()->text('price', 0);
<input type="text" name="price" value=""> // Wrong
<input type="text" name="price" value="0"> // Fixed
// if $model->price == 20 but was specified ZERO as value
html()->text('price', 0);
<input type="text" name="price" value="20"> // Wrong
<input type="text" name="price" value="0"> // Fixed
```
> Fix field population if value is ZERO

- src/Html.php
- tests/Html/InputTest.php
For ease of use, datetime-local should be supported by laravel-html. Date format differs from carbon default.
> add datetime method to support datetime-local

- src/Elements/Input.php
- tests/Html/InputTest.php
Currently `->readonly()` only sets readonly on inputs, as opposed to `->required()`, `->disabled()` and others which accept a bool to toggle the attribute on or off and allow for fluent chaining. This PR brings `->readonly()` in line with the others.
> Add a flag to Input::readonly to toggle readonly-ness.

- docs/general-usage/element-classes.md
This adds all public methods on elements into the documentation.
It removes one (`Select::applyValueToOptions()`) that is currently in the documentation put is actually a protected method.
> Add documentation for elements and methods not currently documented

- docs/general-usage/element-classes.md
- src/Elements/Attributes/Autofocus.php
- src/Elements/Attributes/Disabled.php
- src/Elements/Attributes/MinMaxLength.php
- src/Elements/Attributes/Name.php
- src/Elements/Attributes/Placeholder.php
- src/Elements/Attributes/Readonly.php
- src/Elements/Attributes/Required.php
- src/Elements/Attributes/Type.php
- src/Elements/Attributes/Value.php
- src/Elements/Button.php
- src/Elements/File.php
- src/Elements/Form.php
- src/Elements/Input.php
- src/Elements/Option.php
- src/Elements/Select.php
- src/Elements/Textarea.php
- tests/Elements/FileTest.php
- tests/Elements/FormTest.php
- tests/Elements/InputTest.php
- tests/Elements/SelectTest.php
- tests/Elements/TextareaTest.php
In summary:
This is a fairly large refactor. My goal was to normalise the attribute methods available across elements. As it stands, they vary quite a bit. Some signatures are different, some are present on some elements but not others. I also added some that I use a lot. 27 new tests have been added to account for them all. It's fully backwards compatible with the existing code.
Draft as there are some possible changes that could be made. Namely if the new traits could live in a different namespace or have a different naming scheme. 
In detail:
The following common attributes have been moved into traits:
* Autofocus
* Disabled
* Name
* Placeholder
* Readonly
* Required
* Type
* Value
Attributes that are boolean in nature now universally accept a parameter to toggle them on or off. …
> Normalise common attributes

- docs/general-usage/element-classes.md
- src/Elements/P.php
- src/Html.php
- tests/Elements/PTest.php
This PR is adding <p> as an element. It's a very usual tag, so I thought that it would be nice if we can have it as an element.
I saw in the documentation a few examples with it, but couldn't find that class. Seems to me that it's possible only to create it through "withTag" method.
Sorry if I misunderstood something.
Let me know if you have any suggestions.
Thanks!
> Add p element

- src/Elements/Form.php
This PR simply adds a `Form::route()` method to simplify what is no doubt a very commonly repeated bit of code.
```php
// before
html()->form()->action(route('my_route_name', ['param1', 44]))->open();
//after
html()->form()->route('my_route_name', ['param1', 44])->open();
```
I didn't add any tests as it's just using the `Form::action()` method internally.
> Allow setting a form action to a route

- docs/general-usage/element-classes.md
I was in the process of switching a project from laravelcollective/html to this one, and happened to notice that the readonly() method wasn't working as documented. Digging in, I see the history, that it was renamed in version 3.0.0. This PR simply updates the documentation to reflect that change. In the process of updating the relevant file, I noticed a couple other methods out of order (where they are otherwise alphabetical) so I took the liberty of sneaking in a second commit to reorder those.
> Correction to docs re: readonly vs isReadonly

- src/Html.php
- tests/Html/ModelFormTest.php
- tests/Stubs/Role.php
- tests/Stubs/Status.php
With this PR when casts the model attribute with php native enum, laravel-html gets the enum's value or name for inputs.
> Get value from model with casts php native enum

- src/Html.php
Fixes the following phpstan error:
```
Parameter #1 $contents of method Spatie\Html\Html::div() expects               
Spatie\Html\HtmlElement|string|null, array<int, Spatie\Html\Elements\Element>  
given.      
```
for the given code:
```
html()->div([
html()->p('example'),
html()->p('second child'),
]);
```
This PR updates the docblock of `div` (`html()->div()`) to match the types of `BaseElement::children()` since it just forwards to that function.
> Fix docblock to solve phpstan errors when passing an array to html()->div()

- docs/general-usage/element-classes.md
- src/Elements/Attributes/Autocomplete.php
- src/Elements/Input.php
- src/Elements/Select.php
- src/Elements/Textarea.php
- tests/Elements/InputTest.php
- tests/Elements/SelectTest.php
- tests/Elements/TextareaTest.php
```blade
{{ html()->text('my_column')->placeholder(trans('my_column_placeholder'))->autocomplete('off') }}
```
> Add autocomplete attribute helper to input, select and textarea

- docs/general-usage/core-concepts.md
- docs/general-usage/element-classes.md
- docs/general-usage/extending.md
- docs/general-usage/html-builder.md
- docs/general-usage/the-class-helper.md
- docs/introduction.md
Some links was to old doc version.
I removed version from url. 
Without version user will be redirected anyway to current version
```
https://spatie.be/docs/laravel-html/general-usage/element-methods  -> 
https://spatie.be/docs/laravel-html/v3/general-usage/element-methods
```
> Fix link with version in documentation

- docs/general-usage/element-classes.md
- src/Elements/Form.php
- tests/Elements/FormTest.php
Accidentally omitted from #219. Now all elements that are documented to support the `autocomplete` attribute, support this helper.
> Add autocomplete attribute helper to the form element

- src/BaseElement.php
- tests/Html/ButtonTest.php
I've recently update to laravel/framework 10.19.0 and noticed that it breaks on of my components. 
Error message is: The given child should implement `Spatie\Html\HtmlElement` or be a string
My component looks like this: 
```
<div class="row form-group text-center">
<div class="col-lg-12">
{{
html()
->submit($slot)
->class(['btn', 'btn-primary'] + (($disabled ?? false) ? ['disabled'] : []))
->class($class ?? [])
->id($id ?? 'submit')
->attribute(isset($form) ? 'form' : '', $form ?? '')
->disabled(($disabled ?? false) ? "disabled": "")
}}
</div>
</div>
```
And i use it like this:
```
@component('fc::submit')
{{ __('save') }}
@endcomponent
```
This is my fix for the problem. also reported here: https://github.com/spatie/laravel-html/discussions/193
> Added support for Htmlable contents in BaseElement

- docs/general-usage/element-methods.md
- src/BaseElement.php
- tests/BaseElementTest.php
This PR adds `->aria()` helper method to `BaseElement` for global attributes of multiple aria-* states and properties.
```php
{{ html()->email('email')->aria('describedby', 'emailHelp') }}
```
```html
<input  aria-describedby="emailHelp">
<div id="emailHelp">Email help.</div>
```
> Add aria helper method

- src/BaseElement.php
- tests/BaseElementTest.php
I think it's a useful addition for the blade-style chained invocation.
It allows more elegant conditional configuration of attributes, example:
```blade
{{ html()
->select()
->when($someCondition, fn(BaseElement $element) => $element->data('foo', 'bar'))))
}}
```
> Add Conditionable trait: now `->when()` helper is available on all elements

- src/Html.php
- tests/Html/InputTest.php
I hope the tests run, I don't have the setup locally
> Fix value omitted when input created with no name

- src/Elements/Select.php
This fixes the issue where the select and multiselect of a model's relations are not populated as described here in detail:
https://github.com/spatie/laravel-html/discussions/211
> Fix for Select and model's relationships

- src/BaseElement.php
```bash
[2024-08-09 20:11:06] laravel.WARNING: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /app/vendor/spatie/laravel-html/src/BaseElement.php on line 300  
[2024-08-09 20:11:06] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [deprecations] is not defined. at /app/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:231)
```
My log is filling up with the following message on PHP 8.3.10.
This should fix the warning
> fix: Passing null to parameter #1 ($string) of type string is deprecated

- src/Html.php
- tests/Html/RadioTest.php
There is an issue causing radio buttons with value `0` to be marked as checked.
When `$this->old($name)` is `null` and `$value` is `0`, `null == 0` evaluates true.
Using strict comparison fixes the issue.
> Radio buttons with value 0 are incorrectly marked as checked
