spatie/laravel-html

src/Attributes.php, tests/AttributesTest.php
=> Escape html entities from attribute values + test

composer.json, src/Attributes.php, src/BaseElement.php, src/Elements/Select.php, tests/AttributesTest.php, tests/Elements/SelectTest.php
=> Add placeholder to select

src/Elements/Select.php, tests/Elements/SelectTest.php
=> add empty value to placeholder and update tests

src/Facades/Html.php
=> Fix facade

src/Elements/Optgroup.php, src/Elements/Select.php, tests/Elements/OptgroupTest.php, tests/Elements/SelectTest.php
=> Create Grouped Select List

src/Elements/Input.php, src/Elements/Textarea.php
I love this package, and would like to suggest a small new feature: support for inline styling.
=> Added support for style attribute

src/Html.php, tests/Html/OldTest.php
=> Fix input value check for falsey values

tests/AttributesTest.php, tests/BaseElementTest.php, tests/Elements/FileTest.php, tests/Elements/FormTest.php, tests/Elements/LabelTest.php, tests/Elements/OptgroupTest.php, tests/Html/FieldsetTest.php, tests/Html/FileTest.php, tests/Html/FormTest.php, tests/Html/InputTest.php, tests/Html/LabelTest.php, tests/Html/LegendTest.php, tests/Html/MailToTest.php, tests/Html/ModelFormTest.php, tests/Html/PasswordTest.php, tests/Html/ResetTest.php, tests/Html/SpanTest.php, tests/Html/SubmitTest.php, tests/Html/TelTest.php, tests/Html/TextareaTest.php
This PR aims to improve the test coverage mentioned in #61 :)
=> Improve tests coverage

src/Html.php, tests/Html/OldTest.php
=> Retrieve old data for elements with arrays in names correctly

src/Html.php, tests/Html/RadioTest.php
To fix "0" value cannot be checked
=> Allow radio input check "0" value successfully

.travis.yml, tests/Elements/FormTest.php, tests/Elements/InputTest.php, tests/Html/FormTest.php, tests/Html/ImgTest.php, tests/Html/SelectTest.php
- Add more tests.
- Fix the assertion failure in ```SelectTest``` class.
- Add ```php-7.2``` test in Travis CI build.
=> Test enhancement

src/Elements/Button.php, src/Html.php, tests/Elements/ButtonTest.php, tests/Html/ButtonTest.php
I realized Button element can't take **name** attribute. So i add it.
What i need:
`
<button class="btn btn-primary" type="submit" value="true" name="apply_filter">Filter</button>
`
=> Button Element missing name attribute.

src/Html.php, tests/Html/OldTest.php
I'm sending this patch in order to solve problem reported on issue #139.
This is my first PR on Github, so please let me know if I made some mistake.
=> Prevent password fields to be filled.

src/Html.php, tests/Html/InputTest.php
=> Added number input element generator

docs/general-usage/element-classes.md, src/Elements/Button.php, src/Elements/Fieldset.php, src/Elements/Optgroup.php, src/Elements/Option.php, tests/Elements/ButtonTest.php, tests/Elements/FieldsetTest.php, tests/Elements/OptgroupTest.php, tests/Elements/OptionTest.php
This PR adds the disabled method to all elements that support the attribute according to https://www.w3schools.com/tags/att_disabled.asp
=> Add the disabled method to all elements that support the attribute

docs/general-usage/element-classes.md, src/Elements/A.php, src/Elements/Attributes/Target.php, src/Elements/Form.php, tests/Elements/ATest.php, tests/Elements/FormTest.php, tests/Html/ATest.php, tests/Html/FormTest.php
Title says it all. Includes a trait for the target attribute and tests for the elements where the trait has been applied.
=> Add target attribute to a and form elements

README.md
Remove register provider instructions since there is auto register now
=> Remove register provider instructions since there is auto register now

docs/general-usage/html-builder.md
Adds the documentation I should have added in #189.
=> Add documentation for new FormElement::route() method

docs/installation-setup.md
Specifies how to manually register the service provider in Laravel 11.
=> Register Service Provider in Laravel 11

src/Elements/Form.php, tests/Elements/FormTest.php, tests/Html/FormTest.php
Added name attribute to form element.
=> Add name attribute to form element

src/Html.php
Add use statement and small styling changes.
=> Add use statement

src/Elements/A.php, src/Elements/Img.php
Just discovered this package, looks really cool. :)
=> Add some attributes

src/Elements/File.php, tests/Elements/FileTest.php, tests/Html/FileTest.php
I was missing a way to disable a file input
=> add disabled option to file input
